version: "3"
services:
  bcachefs:
    #image: ubuntu:22.04
    build:
      context: .
      dockerfile: bcachefs.dockerfile
    #restart: always
    environment:
    - DISPLAY=$DISPLAY
    - LANG=C
    - CRON=true
    network_mode: "host"
    container_name: bcachefs
    entrypoint: /root/entry.sh
    working_dir: "/data"
    privileged: true
    #command: "bash"
    #ports:
    #- "9022:22"
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ./root:/root:z
    - ../../mynas_build:/data:z
    deploy:
      resources:
        limits:
          #cpus: '1.5'
          memory: 12G
